# Generated by Django 4.0 on 2022-01-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Control',
            new_name='Contact',
        ),
    ]
